---

- name: Include version-specific variables for OS.
  include_vars: "{{ ansible_os_family|lower }}.yml"

- import_tasks: install.yaml

- import_tasks: config.yaml

- name: Ensure Fluent-Bit is started and enabled at boot.
  service:
    name: fluent-bit
    state: started
    enabled: true
